version: '3.8'
services:
  app:
    build: .
    image: tharun-uthappa
    ports:
      - "3000:3000"
    depends_on:
      - redis
  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data

volumes:
  redis-data: